# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98eda5d2cf0eb19cdf49555b1af26606a16c2e5fe22f095e263c383bdfec4538d2fcb1a3ec53f95bf18f5ea1170b22136a694f1aaaea1472ba05d73594cd9353

test:
  secret_key_base: 0748afcd455030dc0c90c128de15e541e23a0463c4e04ffed81015bdc4612c0fdc54da8dccdc0ce124019846295841db01475a0ebf8d3e5cab8ba464b8eecf5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
